[build-system]
requires = ["scikit-build-core", "pybind11"]
build-backend = "scikit_build_core.build"

[project]
name = "ares-datetime-tests"
version = "0.0.0"
description = "Tests for Ares Common datetime module"
authors = [
    { name = "Tom Schmitz", email = "tschmitz@andrew.cmu.edu" },
]
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
]
dependencies = [
    "pytest"
]