/**
 * @file pyutil.hpp
 *
 * @brief
 *
 * @date 4/14/26
 *
 * @author Tom Schmitz \<tschmitz@andrew.cmu.edu\>
 */

#ifndef ARES_PYUTIL_HPP
#define ARES_PYUTIL_HPP

#include <ares/util.h>
#include <pybind11/pybind11.h>
#include <type_traits>

namespace py = pybind11;

namespace ares {
/**
 * @struct StructParam
 * @tparam T The type of the value
 *
 * @brief Key-value pair for struct parameters.
 *
 * @note This should not be used directly. Instead, use SP().
 */
template <typename T>
struct StructParam {
    const char *name; ///< Struct field name.
    T *value;         ///< Value of that field.
};

template <typename T>
struct is_struct_param : std::false_type {};

template <typename T>
struct is_struct_param<StructParam<T>> : std::true_type {};

/**
 * @brief Converts Python key-word arguments into struct parameters.
 *
 * @tparam Args Variadic pack of NamedValue types generated by SP().
 *
 * @param kwargs The key-word arguments from Python to be processed and
 * converted into struct parameters.
 * @param args The fields to be processed, wrapped in StructParam structs.
 *
 * @note If the input value is `None`, then the default value is used.
 */
template <typename... Args>
void from_kwargs(const py::kwargs &kwargs, Args &&...args) {
    static_assert((is_struct_param<std::decay_t<Args>>::value && ...),
                  "All arguments to from must be wrapped in SP()");

    auto process = [&](auto &&item) {
        if (kwargs.contains(item.name) && !kwargs[item.name].is_none()) {
            using T = std::remove_pointer_t<std::decay_t<decltype(item.value)>>;
            *(item.value) = kwargs[item.name].template cast<T>();
        }
    };

    (process(std::forward<Args>(args)), ...);
}

/**
 * @cond doxygen_suppress
 */
#define Z_SP(field_)                                                           \
    ares::StructParam<decltype(field_)> { #field_, &(field_) }
#define Z_SP_CONTAINER(field_, container_)                                     \
    ares::StructParam<decltype((container_).field_)> {                         \
#field_, &(container_).field_                                          \
    }
/**
 * @endcond
 */

/**
 * @brief Wraps a field into a StructParam struct.
 *
 * Automatically detects if the field is a local variable or a member of a
 * container. If a container is provided, it accesses `container.field_`.
 *
 * @param field_ The name of the variable or member to be wrapped.
 * @param container_ (Optional) The instance containing the field.
 *                   If omitted, the field is treated as a local variable.
 */
#define SP(field_, container_...)                                              \
    COND_CODE_0(IS_EMPTY(container_), (Z_SP_CONTAINER(field_, container_)),    \
                (Z_SP(field_)))

/**
 * @brief Wraps a field into a StructParam struct with a custom name.
 *
 * Used in place of SP() if the python side name is different from the struct
 * parameter name.
 *
 * @param name_ The kwarg key to check for.
 * @param container_ The struct parameter to store the result in.
 */
#define SP_NAMED(name_, container_)                                            \
    ares::StructParam<decltype(container_)> { #name_, &(container_) }

/**
 * @struct NamedValue
 * @tparam T Value type.
 *
 * @brief Key-value pair for struct parameters.
 *
 * @note This should not be used directly. Instead, use NV() OR NV_NO_CHECK().
 */
template <typename T>
struct NamedValue {
    const char *name; ///< Field name.
    const T &value;   ///< Field value.
    bool check;       ///< Flag indicating if a check should be performed.
};

template <typename T>
struct is_named_value : std::false_type {};

template <typename T>
struct is_named_value<NamedValue<T>> : std::true_type {};

/**
 * @brief Converts a variadic list of named values into a Python dictionary with
 * conditional filtering.
 *
 * This overload applies a predicate to each argument. If the argument has its
 * 'check' flag set and the predicate returns true, the value is replaced with a
 * default value (e.g., py::none()). Otherwise, the original value is stored.
 *
 * @tparam Predicate A callable type used to evaluate the value of each field.
 * @tparam Default The type of the fallback value to be used if the check
 * passes.
 * @tparam Args Variadic pack of NamedValue types generated by NV() or
 * NV_NO_CHECK().
 *
 * @param check A lambda or function object defining the condition (e.g.,
 * [](auto v){ return v == 0; }).
 * @param default_val The value to insert into the dict if the check condition
 * is met (e.g., py::none()).
 * @param args The fields to be processed, wrapped in NamedValue structs.
 *
 * @return py::dict A Python dictionary containing the processed key-value
 * pairs.
 */
template <typename Predicate, typename Default, typename... Args,
          typename =
              std::enable_if_t<!is_named_value<std::decay_t<Predicate>>::value>>
py::dict to_dict(Predicate &&check, Default &&default_val, Args &&...args) {
    static_assert(
        (is_named_value<std::decay_t<Args>>::value && ...),
        "All arguments to to_dict must be wrapped in NV() or NV_NO_CHECK()");

    py::dict dict;

    auto process = [&](auto &&item) {
        if (item.check && check(item.value)) {
            dict[item.name] = default_val;
        } else {
            dict[item.name] = item.value;
        }
    };

    (process(std::forward<Args>(args)), ...);
    return dict;
}

/**
 * @brief Converts a variadic list of named values directly into a Python
 * dictionary.
 *
 * This overload maps each NamedValue directly to a dictionary key-value pair
 * without applying any conditional checks or default values.
 *
 * @tparam Args Variadic pack of NamedValue types generated by NV() or
 * NV_NO_CHECK().
 *
 * @param args The fields to be inserted into the dictionary.
 *
 * @return py::dict A Python dictionary containing the exact keys and values
 * provided.
 */
template <typename... Args>
py::dict to_dict(Args &&...args) {
    py::dict dict;
    static_assert(
        (is_named_value<std::decay_t<Args>>::value && ...),
        "All arguments to to_dict must be wrapped in NV() or NV_NO_CHECK()");
    ((dict[args.name] = args.value), ...);
    return dict;
}

/**
 * @cond doxygen_suppress
 */
#define Z_NV(field_, check_)                                                   \
    ares::NamedValue<decltype(field_)> { #field_, field_, check_ }

#define Z_NV_CONTAINER(field_, container_, check_)                             \
    ares::NamedValue<decltype((container_).field_)> {                          \
#field_, (container_).field_, check_                                   \
    }
/**
 * @endcond
 */

/**
 * @brief Wraps a field into a NamedValue struct with checking enabled.
 *
 * Automatically detects if the field is a local variable or a member of a
 * container. If a container is provided, it accesses `container.field_`.
 *
 * @param field_ The name of the variable or member to be wrapped.
 * @param container_ (Optional) The instance containing the field.
 *                   If omitted, the field is treated as a local variable.
 */
#define NV(field_, container_...)                                              \
    COND_CODE_0(IS_EMPTY(container_),                                          \
                (Z_NV_CONTAINER(field_, container_, true)),                    \
                (Z_NV(field_, true)))

/**
 * @brief Wraps a field into a NamedValue struct with checking disabled.
 *
 * Maps a field to a Python dictionary key while explicitly bypassing any
 * conditional logic (like "Zero to None" filtering) in the to_dict template.
 *
 * @param field_ The name of the variable or member to be wrapped.
 * @param container_ (Optional) The instance containing the field.
 *                   If omitted, the field is treated as a local variable.
 */
#define NV_NO_CHECK(field_, container_...)                                     \
    COND_CODE_0(IS_EMPTY(container_),                                          \
                (Z_NV_CONTAINER(field_, container_, false)),                   \
                (Z_NV(field_, false)))

/**
 * Convert an array into a Python tuple.
 * @tparam T The element type of the array.
 * @param data The C++ array to convert into a tuple.
 * @param count The number of items in the array.
 * @return A Python tuple of the array.
 */
template <typename T>
static py::tuple array_to_tuple(const T *data, size_t count) {
    py::tuple t(count);
    for (size_t i = 0; i < count; i++) {
        t[i] = data[i];
    }
    return t;
}
} // namespace ares

#endif // ARES_PYUTIL_HPP
