name: Unit Tests
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: read


jobs:
  Test:
    name: "Unit Testing"
    runs-on: ubuntu-latest

    steps:
      - name: chechout
        uses: actions/checkout@v4
        with:
          path: ares-common

      - name: CMake
        shell: bash
        run: |
          cmake -S ares-common/ -B ares-common-build -DTESTS=ON

      - name: Build
        shell: bash
        run: |
          make

      - name: Unit Test
        working-directory: ares-common-build
        run: |
          ctest -j8 --timeout 120
